name: Measure loading times
on:
    workflow_dispatch:

# When two jobs run in parallel, cancel the older ones
concurrency:
    group: pluto-export
    cancel-in-progress: true

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                julia-version: ["1.6", "1.8", "1.9", "~1.10.0-0"]
                os: [ubuntu-latest, windows-latest]

        steps:
            - name: Checkout this repository
              uses: actions/checkout@v3

            - name: Install Julia
              uses: julia-actions/setup-julia@v1
              with:
                  version: ${{ matrix.julia-version }}

            - name: Get Julia depot path
              id: finddepot
              run: |
                julia -e '
                  println("::set-output name=JULIA_DEPOT::", DEPOT_PATH |> first)'

            - name: Get most downloaded packages
              run: |
                julia -e 'using Pkg
                  Pkg.activate(mktempdir())
                  Pkg.add([
                    Pkg.PackageSpec(name="PlutoSliderServer", version="0.3.2-0.3"),
                  ])

                  import PlutoSliderServer

                  PlutoSliderServer.export_notebook("most_downloaded_packages.jl";
                  )'

            - uses: actions/upload-artifact@v3
              with:
                name: most-popular-packages ${{ matrix.os }} ${{ matrix.julia-version }}
                path: top_packages_sorted_with_deps.txt
            
            - uses: actions/upload-artifact@v3
              with:
                name: most-popular-packages-notebook ${{ matrix.os }} ${{ matrix.julia-version }}
                path: most_downloaded_packages.html
            
            - name: Clear Julia depot
              run: rm -rf ${{ steps.finddepot.outputs.JULIA_DEPOT }}

            - name: 🚀
              run: julia measure_loading_times.jl

            - uses: actions/upload-artifact@v3
              with:
                name: pkg-load-times ${{ matrix.os }} ${{ matrix.julia-version }}
                path: pkg_load_times.csv
                
